---
- name: Roboshop Engine
  hosts: roboshop
  become: true
  gather_facts: true


  roles:
    - pingservice
    - mongodb
    - catalogue
    - cart
    - user
    - redis
    - mysql
    - shipping
    - rabbitmq
    
    

