---
- name: Roboshop Engine
  hosts: roboshop
  become: true
  gather_facts: true


  roles:
    - pingservice

  # tasks:
  #   - name: Pinging All Roboshop Microservices
  #     ansible.builtin.ping:
  #     register: ping_result

  #   - name: Printing Ping Status
  #     ansible.builtin.debug:
  #       var: ping_result
