---
- name: Setting-up Roboshop Mongodb Microservice
  hosts: mongodb
  become: true
  gather_facts: false

  vars:
    log_dir: "/app/logs"
    log_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    log_time: "{{ lookup('pipe', 'date +%H-%M-%S') }}"
    log_file: "{{ log_dir }}/mongodb_{{ log_date }}.log"

  tasks:

    # -----------------------------
    #  LOG DIRECTORY
    # -----------------------------
    - name: Ensure /app/logs directory exists
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'

    # -----------------------------
    #  START LOG
    # -----------------------------
    - name: Log - Playbook Started
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] START: MongoDB Setup started on {{ inventory_hostname }}" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  REPO FILE
    # -----------------------------
    - name: Create MongoDB Repo File
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongo.repo
        owner: root
        group: root
        mode: '0644'
        content: |
          [mongodb-org-4.2]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
          gpgcheck=0
          enabled=1

    - name: Log - Repo File Created/Verified
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] Repo verified/created" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  INSTALL MONGODB
    # -----------------------------
    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Log - MongoDB Installed/Verified
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] MongoDB installation verified" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  UPDATE BIND IP
    # -----------------------------
    - name: Ensure bindIp is set to 0.0.0.0
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        regexp: '^\s*bindIp:'
        line: '  bindIp: 0.0.0.0'
        backrefs: yes

    - name: Log - bindIp Updated/Verified
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] bindIp set to 0.0.0.0" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  ENABLE + START SERVICE
    # -----------------------------
    - name: Enable MongoDB
      ansible.builtin.systemd:
        name: mongod
        enabled: true

    - name: Log - Enabled on Boot
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] MongoDB enabled on boot" >> {{ log_file }}
      changed_when: false

    - name: Start/Restart MongoDB
      ansible.builtin.systemd:
        name: mongod
        state: restarted

    - name: Log - MongoDB Started/Restarted
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] MongoDB service started/restarted" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  END LOG
    # -----------------------------
    - name: Log - Play Completed
      ansible.builtin.shell: |
        echo "[{{ log_date }} {{ log_time }}] END: MongoDB Setup Completed" >> {{ log_file }}
      changed_when: false
