---
- name: Setting-up Roboshop Mongodb Microservice
  hosts: mongodb
  become: true
  gather_facts: false

  vars:
    log_dir: "/app/logs"
    log_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    log_file: "{{ log_dir }}/mongodb_{{ log_timestamp }}.log"

  tasks:

    # -----------------------------
    #  LOG DIRECTORY + START LOG
    # -----------------------------

    - name: Ensure /app/logs directory exists
      ansible.builtin.file:
        path: "{{ log_dir }}"
        state: directory
        mode: '0755'

    - name: Log - Playbook Started
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] START: MongoDB Setup started on {{ inventory_hostname }}" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  CREATE REPO FILE
    # -----------------------------

    - name: Create MongoDB Repo File
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongo.repo
        owner: root
        group: root
        mode: '0644'
        content: |
          [mongodb-org-4.2]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
          gpgcheck=0
          enabled=1

    - name: Log - Repo File Created/Verified
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] Repo file created or verified on {{ inventory_hostname }}" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  INSTALL MONGODB
    # -----------------------------

    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Log - Installation Completed
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] MongoDB installation verified on {{ inventory_hostname }}" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  UPDATE BIND IP
    # -----------------------------

    - name: Ensure bindIp is set to 0.0.0.0
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        regexp: '^\s*bindIp:'
        line: '  bindIp: 0.0.0.0'
        backrefs: yes

    - name: Log - bindIp Updated/Verified
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] bindIp set to 0.0.0.0 on {{ inventory_hostname }}" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  ENABLE + START SERVICE
    # -----------------------------

    - name: Enable MongoDB
      ansible.builtin.systemd:
        name: mongod
        enabled: true

    - name: Log - Enabled
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] MongoDB service enabled on boot" >> {{ log_file }}
      changed_when: false

    - name: Start MongoDB
      ansible.builtin.systemd:
        name: mongod
        state: restarted

    - name: Log - Started
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] MongoDB service started/restarted" >> {{ log_file }}
      changed_when: false

    # -----------------------------
    #  PLAY END LOG
    # -----------------------------

    - name: Log - Play Completed
      ansible.builtin.shell: |
        echo "[{{ log_timestamp }}] END: MongoDB Setup completed on {{ inventory_hostname }}" >> {{ log_file }}
      changed_when: false
