---
- name: Roboshop Redis Microservice Setup
  hosts: redis
  become: yes
  gather_facts: true

  tasks:
    - name: Creating Roboshop App Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Creating Log Directory
      ansible.builtin.file:
        path: /app/log
        state: directory

    - name: Creating Log File
      ansible.builtin.file:
        name: redis_date_time.log
        state: touch

    - name: Creating Roboshop Application User (roboshop)
      ansible.builtin.user:
        name: roboshop
        state: present

    - name: Enable Redis 6 module from AppStream
      ansible.builtin.command: dnf module enable redis:6 -y
      args:
        creates: /etc/dnf/modules.d/redis.module

    - name: Installing Redis from AppStream
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: Modifing Redis BindIP to 0.0.0.0
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: Staring and Enabling Redis Service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
