---
- name: Roboshop Payments Microservice Setup
  hosts: payments
  become: true
  gather_facts: true

  tasks:
  # Basic App Setup
  - name: Creating Roboshop App Directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Creating Roboshop Log Directory
    ansible.builtin.file:
      path: /app/log
      state: directory
  
  - name: Creating Payments Log File
    ansible.builtin.file:
      path: /app/log/payment_date_time.log
      state: touch
  
  - name: Creating Roboshop App User (roboshop)
    ansible.builtin.user:
      name: roboshop
      state: present
  
  - name: Installing Python 3.6 and dependicies
    ansible.builtin.command: "dnf install python36 gcc python3-devel -y"
  
  